---
abstract: 'Be like Yanick when you build your dists'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-YANICK
provides:
  Dist::Zilla::MintingProfile::Author::YANICK:
    file: lib/Dist/Zilla/MintingProfile/Author/YANICK.pm
    version: v0.18.1
  Dist::Zilla::Plugin::Author::YANICK::NextSemanticVersion:
    file: lib/Dist/Zilla/Plugin/Author/YANICK/NextSemanticVersion.pm
    version: v0.18.1
  Dist::Zilla::PluginBundle::YANICK:
    file: lib/Dist/Zilla/PluginBundle/YANICK.pm
    version: v0.18.1
requires:
  CPAN::Changes: 0.17
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::ChangeStats::Git: v0.2.1
  Dist::Zilla::Plugin::CoalescePod: 0
  Dist::Zilla::Plugin::CoderwallEndorse: 0
  Dist::Zilla::Plugin::ContributorsFile: 0
  Dist::Zilla::Plugin::ContributorsFromGit: 0
  Dist::Zilla::Plugin::Covenant: 0
  Dist::Zilla::Plugin::Git: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::HelpWanted: 0
  Dist::Zilla::Plugin::Homepage: 0
  Dist::Zilla::Plugin::InstallGuide: 1.200000
  Dist::Zilla::Plugin::InstallRelease: 0
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaProvides::Package: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::NextVersion::Semantic: v0.1.2
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PreviousVersion::Changelog: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ReadmeMarkdownFromPod: 0
  Dist::Zilla::Plugin::RunExtraTests: 0
  Dist::Zilla::Plugin::SchwartzRatio: 0
  Dist::Zilla::Plugin::Signature: 0
  Dist::Zilla::Plugin::Test::Compile: 2.033
  Dist::Zilla::Plugin::Test::UnusedVars: 0
  Dist::Zilla::Plugin::Twitter: 0.019
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::FileMunger: 0
  Dist::Zilla::Role::MintingProfile::ShareDir: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Dist::Zilla::Role::TextTemplate: 0
  Dist::Zilla::Role::VersionProvider: 0
  Git::Repository: 0
  Moose: 0
  Perl::Version: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-YANICK
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-YANICK/
  repository: https://github.com/yanick/Dist-Zilla-PluginBundle-YANICK.git
version: 0.18.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
